### PR TITLE
EPG Support

### PR DESCRIPTION
**Pull request by alibbaba**
- Removed` communitySources and get_xml_database.
- Add chirppa Livestreamer
- Add custom folder for doEval
- Remove deprecated xbmcgui.ListItem method use setArt:
- EPG support
  -  if its zip file use `<epgfile>[file inside zip]</epgfile>` 
    ```
      <item>
    <title>Cartoon Network</title>
    <link>$doregex[makelist]</link>
    <itemepg>
       <tvgurl>https://...../guide.zip?raw=true</tvgurl>
        <epgfile>guide.xml</epgfile>
        <updateafterhour>15</updateafterhour>
    </itemepg>
    <fanart></fanart>
    </item> 

- if epgfile is not zip then
    ```
   <item>
    <title>Sky Sports 1</title>
    <link>$doregex[makelist]</link>
    <itemepg>
        <<name>Sky Sports 1</name> #this is optional. if used, this will be matched in epg otherwise title will be used.
        <tvgshift></tvgshift>
        <tvgurl>https://../guide.xml?raw=true</tvgurl>
        <updateafterhour>30</updateafterhour>
    </itemepg>
    </item>'''
- if every items in your xml use common epg file, you can simply add this to your file which will look for item info based on <title> tag.
    ```
      <epg>
     <link>https://.../guide.xml</link>
     <updateafterhour>30</updateafterhour>
      </epg>
           Your xml items list ```
- changed getItems function to single item instead of sending items list.
- Improved parse_m3u

### CODE REVIEW

**Comment by Shani-08** [comment]
Thanks for all the changes, i can just take all these changes but shouldn't we do some beta testings? Is it possible for you to ask some guys to give it a go?

**Comment by unlocKing** [comment]
Just a thought, why not add Streamlink as well as livestreamer. 
Livestreamer is great, I use it a lot.. but there is more support with the new Streamlink project:

https://github.com/streamlink

**Comment by alibbaba** [comment]
I agree. So, please dont merge it now. Lets see if there is interest for the EPG, otherwise no point. 

@unlocKing 
livestreamer is abandoned instead we use streamlink.

**Comment by naijaping** [comment]
@alibbaba , thanks for your effort about EPG. really grateful. I am very sure a lot of people want this features.  but we dont know how to make it work.

I have tried something like this  : <channel update="i" site="tvguide.co.uk" site_id="683" xmltv_id="BBC1 HD">BBC One HD</channel>

and this <channel update="i" site="m.dstv.com" site_id="c14cbc61-ca88-43c9-905d-dfec3e481513" xmltv_id="280 ADOM TV">280 ADOM TV</channel> 

in my epg zip but didnt work. i keep checking LSPRO page everyday to see if there is any news on how to make it work.

Can you please elaborate more on which type of epg we need to use in our zip?.

am so sorry for all the troubles.

thanks Bro.

**Comment by unlocKing** [comment]
@alibbaba 
Fantastic! Makes more sense in the long run.. ;)

**Comment by Shani-08** [comment]
Let me know if these are tested and everything is ok before i merge as i can't test all the scenerios.

**Pull request closed without merging**
